import { ILayoutProps } from "@/interfaces/interfaces";
import "@/styles/global.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next13 app/ dir test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ILayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
